language: OCaml

env:
  global:
    secure: bZcUIoyDu8tL8xyO6FL8JjfpRQe2QzzdKav7/V68NVjRxVNuc6FPc+VTchaVtKAfo7iVxjk0krUpyOeQujY3j8uL+ePs7dswGDHY/9trTyGws7NvcCzH+UrR5Yn2TM6I6ill5eHiBiW9W1/eX+K8UiSd/Usk9gZeBjJyz76tZh4=

before_install:
  - sudo add-apt-repository ppa:avsm/ppa -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq ocaml-nox opam
  - opam init -a git://github.com/ocaml/opam-repository && eval $(opam config env)
  - opam install ocamlfind
  - sudo apt-get install -qq gnuplot-nox graphviz
  - sudo apt-get install -qq texlive-latex-recommended tex4ht

script:
  - make all
  - make doc_html
  - make -j2 check

after_success: dev/update-web.sh
