language: OCaml

before_install:
  - sudo add-apt-repository ppa:avsm/ppa -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq ocaml-nox
  - sudo apt-get install -qq  gnuplot-nox graphviz
  - sudo apt-get install -qq  texlive-latex-base texlive-fonts-recommended

script:
  - make all
  - make doc_html
  - make -j2 check
