language: OCaml

before_install:
  - sudo add-apt-repository ppa:avsm/ppa -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq ocaml-nox opam
  - opam init -a git://github.com/ocaml/opam-repository && eval $(opam config env)
  - opam install ocamlfind
  - sudo apt-get install -qq gnuplot-nox graphviz
  - sudo apt-get install -qq texlive-latex-recommended tex4ht

script:
  - make all
  - make doc_html
  - make -j2 check
