language: OCaml

sudo: false

env:
  global:
    secure: bZcUIoyDu8tL8xyO6FL8JjfpRQe2QzzdKav7/V68NVjRxVNuc6FPc+VTchaVtKAfo7iVxjk0krUpyOeQujY3j8uL+ePs7dswGDHY/9trTyGws7NvcCzH+UrR5Yn2TM6I6ill5eHiBiW9W1/eX+K8UiSd/Usk9gZeBjJyz76tZh4=

matrix:
  include:
  - env: CHECKED=webserver
    addons:
      apt:
        sources:
          - avsm
        packages:
          - ocaml-nox
          - opam
  - env: CHECKED=js
    addons:
      apt:
        sources:
          - avsm
        packages:
          - ocaml-nox
          - opam
  - env: USE_TK=1
    addons:
      apt:
        sources:
          - avsm
        packages:
          - ocaml-nox
          - opam
          - tk-dev
  - env: CHECKED=native
    addons:
      apt:
        sources:
          - avsm
        packages:
          - ocaml-nox
          - opam
          - gnuplot-nox
          - graphviz
          - latex-xcolor
          - texlive-latex-recommended
          - tex4ht
  - os: osx

before_install:
  - sh -c "if [ '$TRAVIS_OS_NAME' = osx ] ; then brew update ; brew install opam ; fi"

install:
  - opam init -a git://github.com/ocaml/opam-repository && eval $(opam config env)
  - opam install -y ocamlfind
  - sh -c "if [ '$CHECKED' = js ] ; then opam install -y reactiveData tyxml-ppx js_of_ocaml yojson atdgen ; fi"
  - sh -c "if [ '$CHECKED' = webserver ] ; then opam install -y atdgen lwt cohttp ; fi"
  - sh -c "if [ '$USE_TK' = 1 ] ; then opam install -y labltk ; fi"

script:
  - make all
  - sh -c "if [ '$CHECKED' = native ] ; then make doc_html ; fi"
  - sh -c "if [ '$CHECKED' = native ] ; then make -j2 check ; fi"
  - sh -c "if [ '$CHECKED' = webserver ] ; then make WebSim.native && cd python && python test_kappa_client.py ; fi"
  - sh -c "if [ '$CHECKED' = js ] ; then make site/index.html ; fi"

after_success:
 sh -c "if [ '$TRAVIS_BRANCH' = master ] ; then dev/update-web.sh $CHECKED ; fi"
