language: OCaml

env:
  global:
    secure: bZcUIoyDu8tL8xyO6FL8JjfpRQe2QzzdKav7/V68NVjRxVNuc6FPc+VTchaVtKAfo7iVxjk0krUpyOeQujY3j8uL+ePs7dswGDHY/9trTyGws7NvcCzH+UrR5Yn2TM6I6ill5eHiBiW9W1/eX+K8UiSd/Usk9gZeBjJyz76tZh4=
  matrix:
    - CHECKED=js
    - CHECKED=native

before_install:
  - sudo add-apt-repository ppa:avsm/ppa -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq ocaml-nox opam
  - sh -c "if [ '$CHECKED' = js ] ; then sudo apt-get install -qq camlp4-extra ; fi"
  - opam init -a git://github.com/ocaml/opam-repository && eval $(opam config env)
  - opam install ocamlfind
  - sh -c "if [ '$CHECKED' = js ] ; then opam install -y reactiveData tyxml js_of_ocaml ; fi"
  - sh -c "if [ '$CHECKED' = native ] ; then sudo apt-get install -qq gnuplot-nox graphviz ; fi"
  - sh -c "if [ '$CHECKED' = native ] ; then sudo apt-get install -qq texlive-latex-recommended tex4ht ; fi"

script:
  - make all
  - sh -c "if [ '$CHECKED' = native ] ; then make doc_html ; fi"
  - sh -c "if [ '$CHECKED' = native ] ; then make -j2 check ; fi"
  - sh -c "if [ '$CHECKED' = js ] ; then make js/JaSim.js ; fi"

after_success: dev/update-web.sh $CHECKED
